### ISSUE TITLE
How about service-locator-dns

### ISSUE THREAD

**Issue by huntc** [AlexanderRay/lagom-on-kube#2]
Why not just use https://github.com/typesafehub/service-locator-dns#service-locator-dns? I wrote it with Kubernetes/Lagom integration in mind.

**Comment by AlexanderRay** [comment]
The decision to use **service-locator** based on **devmode-components** instead of **service-locator-dns** is based on following points:

-  there is a central registry from all of the **lagom-services**, that means that some external services can discover **lagom-services** and list, monitor etc. them
- there is a gateway, a central entry point to all of the **lagom-services** that is useful in general

But I see your point, and there can be some scenarios in which a central registry or a central entry point are not necessary, and I would be very thankful if you make a pull request that round up the tutorial with examples how to use **service-locator-dns** with that demo services

**Comment by huntc** [comment]
You shouldn't assume a central registry from dev mode. Lagom services can lookup other services outside of those defined by its repo. 

service-locator-dns should be easy to add. Just add the lib to your project.

**Comment by AlexanderRay** [comment]
I think you misunderstood me. My solution is **not** a registry from dev mode, it is **based on** dev mode

I see al least two possible solutions how to do a **service discovery** in kubernetes cluster

- with a **central service registry**, which can be solved by
  - [ETCD](https://github.com/coreos/etcd)
  - [Consul](https://www.consul.io/)
  - or any custom solution, for example by **akka peristence** and **cassandra** 
- without a **central service registry** using some of underlying tools, 
  - kube-dns (your solution)
  - kubernates api 
  - ...

Both ways have pros and contras.  

As I mentioned above central registry provides at least a central **entry point** and a **gateway** to the services, but is also a **single point of failure** that should be considered by the infrastructure. 

Your solution, on other hand, haven't such kinds of disadvantages (or they are solved by kubernetes itself), but it's more simpler, have some configuration overhead and can be used only in certain scenarios.

And as I said, you could round up the tutorial with your solution. That implies 
- differences between the two approaches; contexts in which each of them is better suitable
- detailed configurations for Kube and Ansible
- examples of services using each of the solutions
- ...

**Comment by huntc** [comment]
KubeDNS is a central registry... anyhow my main point was to make you aware of the simplest approach for Lagom that leverages what is built in for k8s. I'll close this ticket as I think you are at least aware of the service-locator-dns project.
